add ibc-relayer assets
neutron-org/neutron-assets pull request #2
Opened 2022-10-03 08:07 UTC by NeverHappened

2022-10-03 09:36 UTC, albertandrejev requested changes

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/config.toml
> +trusting_period = '10days'
Our unbonding period is [21 days ](https://github.com/neutron-org/neutron-assets/blob/5b9171c1f9dadd2ffc42b23e5a040d014ee09c8e/neutron-devnet-1/genesis.json#L473). And it is [recommended](https://hermes.informal.systems/example-config.html) to have trusting period to equal 2/3 of unbonding period. 
We can lower unbonding period of course or increase trusting period.

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/config.toml
> +trusting_period = '10days'
Good for osmo.

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/neutron-relayer-mnemonic.txt
> +pencil spend approve lift cheap raw exhaust such wine obey gospel shop swim fee tomorrow entire special swear jump upset awful blame glove license
Not sure it is good to store mnemonic here :( some pranksters can mock and transfer coins from relayer address to somewhere else which may lead to hard-to-understand situations.

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/osmosis-relayer-mnemonic.txt
> +usage love fee cash cotton cinnamon shallow bulb swallow velvet build food harvest first wash accuse soldier interest polar length dial wrestle test ignore
Same here

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/test_ibc_transfer.sh
> +BIN=neutrond
maybe it is better to use full path?

2022-10-03 09:36 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/test_interchain_txs.sh
> +NEUTRON_ADDRESS_MNEMONIC="spy crowd swamp juice walnut earth century job flip tuna ready voice goose fiber away upgrade seven draft smooth visual shrug same gallery hero"
Do we need to run `test_interchain_txs.sh` and `test_ibc_transfer.sh` in predefined order, one after another?
Also, is it possible to avoid usage of mnemonic here?

2022-10-03 13:35 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/test_ibc_transfer.sh
> +BIN=neutrond
full path is different on different machines. I assume you added `neutrond` to PATH.
And it's a test stuff, more like to proof that it works. I did not try to prettify it yet.

2022-10-03 13:44 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/neutron-relayer-mnemonic.txt
> +pencil spend approve lift cheap raw exhaust such wine obey gospel shop swim fee tomorrow entire special swear jump upset awful blame glove license
No

2022-10-03 15:33 UTC, foxpy commented on neutron-devnet-1/ibc-relayer/neutron-relayer-mnemonic.txt
> +pencil spend approve lift cheap raw exhaust such wine obey gospel shop swim fee tomorrow entire special swear jump upset awful blame glove license
yep, please generate new mnemonic and drop this one :)

2022-10-07 09:05 UTC, albertandrejev requested changes

2022-10-07 09:05 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/config.toml
> +trusting_period = '1days'
Please change it to more suitable value (2/3 from chain unbonding period)

2022-10-07 10:55 UTC, oopcode commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
why seconds?..

2022-10-07 12:07 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
it's 2/3 of a 2 days, then, I though that it's a big difference between 1 day and a 1day and 8 hours.

2022-10-07 12:07 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
I can change to 1 day or course)

2022-10-07 12:39 UTC, oopcode commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
on gaia testnet the unbonding period is2 days?

2022-10-07 12:52 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
> on gaia testnet the unbonding period is2 days?

on Juno testnet

2022-10-07 12:56 UTC, albertandrejev commented on neutron-devnet-1/ibc-relayer/test_interchain_txs.sh
> +# Upload the queries contract
nit: can you `echo` this and other similar comments to stdout? In this case it is easier to read script output.

2022-10-07 12:58 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
yeah

2022-10-07 14:45 UTC, foxpy commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
Please leave a human readable amount in a comment then

2022-10-10 07:01 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
Hm, I can use hours probably

2022-10-10 07:05 UTC, NeverHappened commented on neutron-devnet-1/ibc-relayer/config.toml
> +# trusting_period = '115200s'
Done

2022-10-10 10:16 UTC, albertandrejev approved these changes

2022-10-12 08:21 UTC, oopcode approved these changes

2022-10-12 08:21 UTC, merged